name: ContanarizedDockerBuild

on: workflow_dispatch

jobs:
  Docker_Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ vars.USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Build
      run: docker build -t ${{ vars.USERNAME }}/git-action-images:pythonimage .

    - name: Docker Push
      run: docker push ${{ vars.USERNAME }}/git-action-images:pythonimage
