name: non-contanarized Build

on: 
 workflow_dispatch

jobs:
  Py_Build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v6.0.2
     
     - name: setup/install python dependiencies
       uses: actions/setup-python@v6.2.0
       with:
        run: python -m pip install            # installing dependencies
     
     - name: .py build                            
       run: |
        python -m py_compile src/main.py          # Byte-compiles .py â†’ .pyc (optional)
        echo "Python build successful"

     - name: Run and Test 
       run: python src/main.py
     
     - name: publish artifact
       uses: actions/upload-artifact@v6.0.0
       with:
        name: Package
        mkdir: staging
        path: staging
       
  
  

   
