name: non-contanarized Build

on: 
 workflow_dispatch

jobs:
  Py_Build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v6.0.2
     
     - name: setup/install python dependiencies
       uses: actions/setup-python@v6.2.0
       with:
        python-version: '3.11'
        run: python -m pip install            # installing dependencies
     
                                                                                                                                
     - name: Run and Test 
       run: python src/main.py


     - name: Run Python script
       run: |
          mkdir -p staging
          python src/main.py > staging/output.txt

     - name: Upload artifact
       uses: actions/upload-artifact@v4
       with:
          name: python-output
          path: staging/

       
  
  

   
